---
- name: Validate Docker is started
  ansible.builtin.service:
    name: 'docker'
    state: started

- name: Configure monitoring network
  community.docker.docker_network:
    name: monitoring

- name: Mount storage
  ansible.posix.mount:
    src: UUID=ae4d940e-021b-4921-b50e-7e852b717bb1
    path: /media/pi/raspberry-pi
    fstype: ext4
    opts: defaults,auto,users,rw,nofail
    state: mounted

# Configure InfluxDB
- import_tasks: influxdb.yml
  tags:
    - influxdb

# Configure Grafana
- import_tasks: grafana.yml
  tags:
    - grafana

# Configure Telegraf
- import_tasks: telegraf.yml
  tags:
    - telegraf
