---

- hosts: all
  become: yes
  roles:
  - { role: os-patching, tags: patching }

  tasks:
  - name: Congratulations!
    debug:
      msg:
        - "The distro is: {{ ansible_distribution|lower }} and the version name is: {{ ansible_distribution_release }}"
