---

- name: 'Base Setup'
  hosts: all
  tasks:
    - import_role:
        name: os_patching
      tags:
        - all
        - patching
    - import_role:
        name: docker
      tags:
        - all
        - docker
    - import_role:
        name: influxdb
      tags:
        - all
        - influxdb
    - debug:
        msg:
        - "The distro is: {{ ansible_distribution|lower }} and the version name is: {{ ansible_distribution_release }}"
