---

- name: Updating the system's package list
  apt:
    update_cache: yes

- name: Upgrading all installed system packages to their latest versions
  apt:
    upgrade: dist

- name: Installing additional required packages
  apt:
    pkg:
      - python3
      - python3-pip
