---
- name: Restart InfluxDB
  community.docker.docker_container:
    name: influxdb
    image: influxdb:{{ influxdb_version }}
    container_default_behavior: no_defaults
    state: started
    volumes:
      - "/media/pi/raspberry-pi/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf"
      - "/media/pi/raspberry-pi/influxdb/data:/var/lib/influxdb"
    published_ports:
      - "8086:8086"
