---
- name: Update the apt package index
  ansible.builtin.apt:
    update_cache: yes

- name: Install packages to allow apt to use a repository over HTTPS
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
    state: latest

- name: Add Docker’s official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: Add the Docker apt repo
  ansible.builtin.apt_repository:
    filename: docker
    repo: deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present
    update_cache: yes

- name: Install the latest version of Docker and containerd
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: yes
  notify: Start Docker
